<?php

declare(strict_types=1);

namespace Infrastructure\Lowcode\Collection\Service;

use Domain\Lowcode\Collection\Interfaces\CollectionInterface;

/**
 * Migration Manager Service | 迁移管理服务
 *
 * Auto-generates migration files for collections.
 * 自动为集合生成迁移文件。
 *
 * @package Infrastructure\Lowcode\Collection\Service
 */
class MigrationManager
{
    protected string $migrationsPath;

    /**
     * Constructor | 构造函数
     */
    public function __construct()
    {
        $this->migrationsPath = root_path() . 'database/migrations/';
    }

    /**
     * Generate migration file for collection | 为Collection生成迁移文件
     *
     * @param CollectionInterface $collection Collection | Collection
     * @return string Migration file path | 迁移文件路径
     */
    public function generateMigration(CollectionInterface $collection): string
    {
        $className = 'Create' . $this->studly($collection->getTableName()) . 'Table';
        $timestamp = date('YmdHis');
        $filename = "{$timestamp}_{$this->snake($className)}.php";
        $filepath = $this->migrationsPath . $filename;

        $content = $this->buildMigrationContent($collection, $className);

        file_put_contents($filepath, $content);

        return $filepath;
    }

    /**
     * Build migration file content | 构建迁移文件内容
     *
     * @param CollectionInterface $collection Collection | Collection
     * @param string $className Class name | 类名
     * @return string Migration file content | 迁移文件内容
     */
    protected function buildMigrationContent(CollectionInterface $collection, string $className): string
    {
        $tableName = $collection->getTableName();
        $fieldsCode = $this->buildFieldsCode($collection);

        return <<<PHP
<?php

use think\migration\Migrator;
use think\migration\db\Column;

/**
 * Migration for {$tableName} table | {$tableName}表迁移
 * 
 * Auto-generated by MigrationManager.
 * 由MigrationManager自动生成。
 */
class {$className} extends Migrator
{
    /**
     * Create table | 创建表
     */
    public function change()
    {
        \$table = \$this->table('{$tableName}', [
            'id' => 'id',
            'engine' => 'InnoDB',
            'collation' => 'utf8mb4_unicode_ci',
            'comment' => '{$collection->getTitle()}',
        ]);

        \$table
            ->addColumn('id', 'integer', [
                'signed' => false,
                'identity' => true,
                'comment' => 'Primary key | 主键',
            ])
{$fieldsCode}
            ->addColumn('created_at', 'datetime', [
                'default' => 'CURRENT_TIMESTAMP',
                'comment' => 'Created at | 创建时间',
            ])
            ->addColumn('updated_at', 'datetime', [
                'default' => 'CURRENT_TIMESTAMP',
                'update' => 'CURRENT_TIMESTAMP',
                'comment' => 'Updated at | 更新时间',
            ])
            ->create();
    }
}

PHP;
    }

    /**
     * Build fields code for migration | 为迁移构建字段代码
     *
     * @param CollectionInterface $collection Collection | Collection
     * @return string Fields code | 字段代码
     */
    protected function buildFieldsCode(CollectionInterface $collection): string
    {
        $code = '';

        foreach ($collection->getFields() as $field) {
            $type = $this->mapToMigrationType($field->getDbType());
            $nullable = $field->isNullable() ? 'true' : 'false';
            $default = $field->getDefault() !== null ? "'{$field->getDefault()}'" : 'null';

            $code .= "            ->addColumn('{$field->getName()}', '{$type}', [\n";
            $code .= "                'null' => {$nullable},\n";
            if ($field->getDefault() !== null) {
                $code .= "                'default' => {$default},\n";
            }
            $code .= "                'comment' => '{$field->getTitle()} | {$field->getType()}',\n";
            $code .= "            ])\n";
        }

        return $code;
    }

    /**
     * Map database type to migration type | 映射数据库类型到迁移类型
     *
     * @param string $dbType Database type | 数据库类型
     * @return string Migration type | 迁移类型
     */
    protected function mapToMigrationType(string $dbType): string
    {
        if (str_contains($dbType, 'VARCHAR')) {
            return 'string';
        }
        if (str_contains($dbType, 'TEXT')) {
            return 'text';
        }
        if (str_contains($dbType, 'INT')) {
            return 'integer';
        }
        if (str_contains($dbType, 'DECIMAL')) {
            return 'decimal';
        }
        if (str_contains($dbType, 'DATETIME')) {
            return 'datetime';
        }
        if (str_contains($dbType, 'DATE')) {
            return 'date';
        }
        if (str_contains($dbType, 'TIMESTAMP')) {
            return 'timestamp';
        }
        if (str_contains($dbType, 'JSON')) {
            return 'text';
        }

        return 'string';
    }

    /**
     * Convert string to StudlyCase | 转换字符串为驼峰命名
     */
    protected function studly(string $value): string
    {
        $value = ucwords(str_replace(['-', '_'], ' ', $value));
        return str_replace(' ', '', $value);
    }

    /**
     * Convert string to snake_case | 转换字符串为下划线命名
     */
    protected function snake(string $value): string
    {
        $value = preg_replace('/\s+/u', '', ucwords($value));
        return strtolower(preg_replace('/(.)(?=[A-Z])/u', '$1_', $value));
    }
}
